const AATROX = "AATROX";
const AHRI = "AHRI";
const AKALI = "AKALI";
const AKSHAN = "AKSHAN";
const ALISTAR = "ALISTAR";
const AMUMU = "AMUMU";
const ANIVIA = "ANIVIA";
const ANNIE = "ANNIE";
const APHELIOS = "APHELIOS";
const ASHE = "ASHE";
const AURELION_SOL = "AURELION SOL";
const AZIR = "AZIR";
const BARD = "BARD";
const BEL_VETH = "BEL'VETH";
const BLITZCRANK = "BLITZCRANK";
const BRAND = "BRAND";
const BRAUM = "BRAUM";
const CAITLYN = "CAITLYN";
const CAMILLE = "CAMILLE";
const CASSIOPEIA = "CASSIOPEIA";
const CHO_GATH = "CHO'GATH";
const CORKI = "CORKI";
const DARIUS = "DARIUS";
const DIANA = "DIANA";
const DR_MUNDO = "DR. MUNDO";
const DRAVEN = "DRAVEN";
const EKKO = "EKKO";
const ELISE = "ELISE";
const EVELYNN = "EVELYNN";
const EZREAL = "EZREAL";
const FIDDLESTICKS = "FIDDLESTICKS";
const FIORA = "FIORA";
const FIZZ = "FIZZ";
const GALIO = "GALIO";
const GANGPLANK = "GANGPLANK";
const GAREN = "GAREN";
const GNAR = "GNAR";
const GRAGAS = "GRAGAS";
const GRAVES = "GRAVES";
const GWEN = "GWEN";
const HECARIM = "HECARIM";
const HEIMERDINGER = "HEIMERDINGER";
const ILLAOI = "ILLAOI";
const IRELIA = "IRELIA";
const IVERN = "IVERN";
const JANNA = "JANNA";
const JARVAN_IV = "JARVAN IV";
const JAX = "JAX";
const JAYCE = "JAYCE";
const JHIN = "JHIN";
const JINX = "JINX";
const KAI_SA = "KAI'SA";
const KALISTA = "KALISTA";
const KARMA = "KARMA";
const KARTHUS = "KARTHUS";
const KASSADIN = "KASSADIN";
const KATARINA = "KATARINA";
const KAYLE = "KAYLE";
const KAYN = "KAYN";
const KENNEN = "KENNEN";
const KHA_ZIX = "KHA'ZIX";
const KINDRED = "KINDRED";
const KLED = "KLED";
const KOG_MAW = "KOG'MAW";
const LEBLANC = "LEBLANC";
const LEE_SIN = "LEE SIN";
const LEONA = "LEONA";
const LILLIA = "LILLIA";
const LISSANDRA = "LISSANDRA";
const LUCIAN = "LUCIAN";
const LULU = "LULU";
const LUX = "LUX";
const MALPHITE = "MALPHITE";
const MALZAHAR = "MALZAHAR";
const MAOKAI = "MAOKAI";
const MASTER_YI = "MASTER YI";
const MISS_FORTUNE = "MISS FORTUNE";
const MORDEKAISER = "MORDEKAISER";
const MORGANA = "MORGANA";
const NAMI = "NAMI";
const NASUS = "NASUS";
const NAUTILUS = "NAUTILUS";
const NEEKO = "NEEKO";
const NIDALEE = "NIDALEE";
const NOCTURNE = "NOCTURNE";
const NUNU_WILLUMP = "NUNU & WILLUMP";
const OLAF = "OLAF";
const ORIANNA = "ORIANNA";
const ORNN = "ORNN";
const PANTHEON = "PANTHEON";
const POPPY = "POPPY";
const PYKE = "PYKE";
const QIYANA = "QIYANA";
const QUINN = "QUINN";
const RAKAN = "RAKAN";
const RAMMUS = "RAMMUS";
const REK_SAI = "REK'SAI";
const RELL = "RELL";
const RENATA_GLASC = "RENATA GLASC";
const RENEKTON = "RENEKTON";
const RENGAR = "RENGAR";
const RIVEN = "RIVEN";
const RUMBLE = "RUMBLE";
const RYZE = "RYZE";
const SAMIRA = "SAMIRA";
const SEJUANI = "SEJUANI";
const SENNA = "SENNA";
const SERAPHINE = "SERAPHINE";
const SETT = "SETT";
const SHACO = "SHACO";
const SHEN = "SHEN";
const SHYVANA = "SHYVANA";
const SINGED = "SINGED";
const SION = "SION";
const SIVIR = "SIVIR";
const SKARNER = "SKARNER";
const SONA = "SONA";
const SORAKA = "SORAKA";
const SWAIN = "SWAIN";
const SYLAS = "SYLAS";
const SYNDRA = "SYNDRA";
const TAHM_KENCH = "TAHM KENCH";
const TALIYAH = "TALIYAH";
const TALON = "TALON";
const TARIC = "TARIC";
const TEEMO = "TEEMO";
const THRESH = "THRESH";
const TRISTANA = "TRISTANA";
const TRUNDLE = "TRUNDLE";
const TRYNDAMERE = "TRYNDAMERE";
const TWISTED_FATE = "TWISTED FATE";
const TWITCH = "TWITCH";
const UDYR = "UDYR";
const URGOT = "URGOT";
const VARUS = "VARUS";
const VAYNE = "VAYNE";
const VEIGAR = "VEIGAR";
const VEL_KOZ = "VEL'KOZ";
const VEX = "VEX";
const VI = "VI";
const VIEGO = "VIEGO";
const VIKTOR = "VIKTOR";
const VLADIMIR = "VLADIMIR";
const VOLIBEAR = "VOLIBEAR";
const WARWICK = "WARWICK";
const WUKONG = "WUKONG";
const XAYAH = "XAYAH";
const XERATH = "XERATH";
const XIN_ZHAO = "XIN ZHAO";
const YASUO = "YASUO";
const YONE = "YONE";
const YORICK = "YORICK";
const YUUMI = "YUUMI";
const ZAC = "ZAC";
const ZED = "ZED";
const ZERI = "ZERI";
const ZIGGS = "ZIGGS";
const ZILEAN = "ZILEAN";
const ZOE = "ZOE";
const ZYRA = "ZYRA";

const IT_HAS_ULTIMATE_IN_THE_NAME = "IT_HAS_ULTIMATE_IN_THE_NAME";
const IT_HAS_ULTIMATE_IN_THE_NAME_CHAMPS = [
  AMUMU,
  ANNIE,
  AURELION_SOL,
  AZIR,
  BARD,
  BLITZCRANK,
  BRAUM,
  CASSIOPEIA,
  CORKI,
  DIANA,
  DRAVEN,
  EKKO,
  EZREAL,
  FIDDLESTICKS,
  FIZZ,
  GALIO,
  GANGPLANK,
  GNAR,
  GRAGAS,
  GRAVES,
  HECARIM,
  HEIMERDINGER,
  ILLAOI,
  JANNA,
  JARVAN_IV,
  JINX,
  KARTHUS,
  KATARINA,
  KAYLE,
  KENNEN,
  LEONA,
  LISSANDRA,
  LUX,
  MALPHITE,
  MAOKAI,
  MISS_FORTUNE,
  MORGANA,
  NAMI,
  NEEKO,
  NUNU_WILLUMP,
  ORIANNA,
  ORNN,
  PANTHEON,
  RAKAN,
  RAMMUS,
  RELL,
  RIVEN,
  RUMBLE,
  SAMIRA,
  SEJUANI,
  SENNA,
  SERAPHINE,
  SETT,
  SONA,
  SWAIN,
  TALON,
  TWITCH,
  VEL_KOZ,
  VIKTOR,
  VLADIMIR,
  VOLIBEAR,
  XAYAH,
  XIN_ZHAO,
  YONE,
  YUUMI,
  ZAC,
  ZIGGS,
  ZYRA,
];

const GET_OVER_HERE = "GET_OVER_HERE";
const GET_OVER_HERE_CHAMPS = [
  ALISTAR,
  AURELION_SOL,
  AZIR,
  BLITZCRANK,
  DARIUS,
  GNAR,
  GRAGAS,
  HECARIM,
  JANNA,
  JAYCE,
  KLED,
  LEE_SIN,
  MAOKAI,
  MORDEKAISER,
  NAUTILUS,
  ORIANNA,
  POPPY,
  PYKE,
  RELL,
  SETT,
  SINGED,
  SKARNER,
  SWAIN,
  TAHM_KENCH,
  TALIYAH,
  THRESH,
  TRISTANA,
  URGOT,
  VAYNE,
  XIN_ZHAO,
  YONE,
  ZAC,
  ZIGGS,
];

const HOLD_THAT_POSE = "HOLD_THAT_POSE";
const HOLD_THAT_POSE_CHAMPS = [
  AATROX,
  ALISTAR,
  AMUMU,
  ANIVIA,
  AURELION_SOL,
  BARD,
  BLITZCRANK,
  BRAUM,
  CAMILLE,
  GALIO,
  GNAR,
  GRAGAS,
  HECARIM,
  IVERN,
  JANNA,
  JARVAN_IV,
  KLED,
  LEBLANC,
  LEONA,
  LISSANDRA,
  LULU,
  MAOKAI,
  MORGANA,
  NAMI,
  NAUTILUS,
  NEEKO,
  NUNU_WILLUMP,
  ORNN,
  POPPY,
  PYKE,
  RAMMUS,
  RELL,
  RIVEN,
  SEJUANI,
  SERAPHINE,
  SETT,
  SHACO,
  SINGED,
  SION,
  SKARNER,
  TAHM_KENCH,
  THRESH,
  URGOT,
  VI,
  WARWICK,
  XIN_ZHAO,
  YASUO,
  YONE,
  ZAC,
  ZYRA,
];

const WERE_GOOD_OVER_HERE = "WERE_GOOD_OVER_HERE";
const WERE_GOOD_OVER_HERE_CHAMPS = [
  AKSHAN,
  ASHE,
  AZIR,
  CAITLYN,
  CHO_GATH,
  CORKI,
  DR_MUNDO,
  EZREAL,
  GANGPLANK,
  JAYCE,
  JHIN,
  JINX,
  KAI_SA,
  KARMA,
  KLED,
  KOG_MAW,
  LUX,
  MAOKAI,
  NIDALEE,
  PANTHEON,
  SENNA,
  SERAPHINE,
  SHYVANA,
  SIVIR,
  TALIYAH,
  TWISTED_FATE,
  VARUS,
  VEL_KOZ,
  VEX,
  VIKTOR,
  XAYAH,
  XERATH,
  YUUMI,
  ZIGGS,
  ZOE,
];

const NOWHERE_TO_HIDE = "NOWHERE_TO_HIDE";
const NOWHERE_TO_HIDE_CHAMPS = [
  AKSHAN,
  ASHE,
  BARD,
  CAITLYN,
  DRAVEN,
  EZREAL,
  GALIO,
  GANGPLANK,
  JHIN,
  JINX,
  KAI_SA,
  KARTHUS,
  KLED,
  LILLIA,
  LUX,
  MAOKAI,
  NOCTURNE,
  PANTHEON,
  RYZE,
  SENNA,
  SHEN,
  SION,
  SORAKA,
  SWAIN,
  TALIYAH,
  TWISTED_FATE,
  VEX,
  XERATH,
  ZIGGS,
];

const WE_PROTEC = "WE_PROTEC";
const WE_PROTEC_CHAMPS = [
  ALISTAR,
  ANNIE,
  BARD,
  FIORA,
  GALIO,
  IVERN,
  JANNA,
  KARMA,
  KAYLE,
  KINDRED,
  LEE_SIN,
  LULU,
  LUX,
  MORGANA,
  NAMI,
  NIDALEE,
  ORIANNA,
  RAKAN,
  RELL,
  SENNA,
  SERAPHINE,
  SHEN,
  SONA,
  SORAKA,
  TAHM_KENCH,
  TARIC,
  THRESH,
  YUUMI,
  ZILEAN,
];

const ITS_A_TRAP = "ITS_A_TRAP";
const ITS_A_TRAP_CHAMPS = [
  CAITLYN,
  GANGPLANK,
  JHIN,
  JINX,
  MAOKAI,
  NIDALEE,
  SHACO,
  TEEMO,
  ZIGGS,
  ZYRA,
];

const THEY_JUST_DONT_DIE = "THEY_JUST_DONT_DIE";
const THEY_JUST_DONT_DIE_CHAMPS = [
  AKSHAN,
  ALISTAR,
  ANIVIA,
  BARD,
  BRAUM,
  EKKO,
  ELISE,
  EVELYNN,
  FIORA,
  FIZZ,
  GWEN,
  JAX,
  KALISTA,
  KARTHUS,
  KAYLE,
  KAYN,
  KINDRED,
  KLED,
  KOG_MAW,
  LISSANDRA,
  MALZAHAR,
  MAOKAI,
  MASTER_YI,
  OLAF,
  PANTHEON,
  RAKAN,
  SION,
  TAHM_KENCH,
  TARIC,
  TRYNDAMERE,
  VLADIMIR,
  XIN_ZHAO,
  YUUMI,
  ZAC,
  ZED,
  ZILEAN,
];

const WHERED_THEY_GO = "WHERED_THEY_GO";
const WHERED_THEY_GO_CHAMPS = [
  AKALI,
  AKSHAN,
  EVELYNN,
  KAI_SA,
  KHA_ZIX,
  LEBLANC,
  NEEKO,
  NOCTURNE,
  PYKE,
  RENGAR,
  SENNA,
  SHACO,
  TALON,
  TEEMO,
  TWITCH,
  VAYNE,
  VIEGO,
];

const SUMMONERS_ON_THE_RIFT = "SUMMONERS_ON_THE_RIFT";
const SUMMONERS_ON_THE_RIFT_CHAMPS = [
  ANNIE,
  AZIR,
  ELISE,
  FIDDLESTICKS,
  HEIMERDINGER,
  ILLAOI,
  IVERN,
  KALISTA,
  KINDRED,
  LISSANDRA,
  MALZAHAR,
  MAOKAI,
  NEEKO,
  ORIANNA,
  SHACO,
  YORICK,
  ZED,
  ZYRA,
];

const IM_HELPING = "IM_HELPING";
const IM_HELPING_CHAMPS = [
  ANIVIA,
  AZIR,
  IRELIA,
  IVERN,
  JARVAN_IV,
  ORNN,
  TALIYAH,
  TRUNDLE,
  VEIGAR,
  YORICK,
];

const FIVE_UNDER_FIVE = "FIVE_UNDER_FIVE";
const FIVE_UNDER_FIVE_CHAMPS = [
  CORKI,
  FIZZ,
  GNAR,
  HEIMERDINGER,
  KLED,
  LULU,
  POPPY,
  RUMBLE,
  TEEMO,
  TRISTANA,
  VEIGAR,
  VEX,
  YUUMI,
  ZIGGS,
];

const FOR_DEMACIA = "FOR_DEMACIA";
const FOR_DEMACIA_CHAMPS = [
  FIORA,
  GALIO,
  GAREN,
  JARVAN_IV,
  KAYLE,
  LUCIAN,
  LUX,
  MORGANA,
  POPPY,
  QUINN,
  SHYVANA,
  SONA,
  SYLAS,
  VAYNE,
  XIN_ZHAO,
];

const ICE_ICE_BABY = "ICE_ICE_BABY";
const ICE_ICE_BABY_CHAMPS = [
  ANIVIA,
  ASHE,
  BRAUM,
  GNAR,
  GRAGAS,
  LISSANDRA,
  NUNU_WILLUMP,
  OLAF,
  ORNN,
  SEJUANI,
  TRUNDLE,
  TRYNDAMERE,
  UDYR,
  VOLIBEAR,
];

const EVERYBODY_WAS_WUJU_FIGHTING = "EVERYBODY_WAS_WUJU_FIGHTING";
const EVERYBODY_WAS_WUJU_FIGHTING_CHAMPS = [
  AHRI,
  AKALI,
  IRELIA,
  IVERN,
  JHIN,
  KARMA,
  KAYN,
  KENNEN,
  LEE_SIN,
  LILLIA,
  MASTER_YI,
  RAKAN,
  SETT,
  SHEN,
  SYNDRA,
  VARUS,
  WUKONG,
  XAYAH,
  YASUO,
  YONE,
  ZED,
];

const THE_SUN_DISC_NEVER_SETS = "THE_SUN_DISC_NEVER_SETS";
const THE_SUN_DISC_NEVER_SETS_CHAMPS = [
  AKSHAN,
  AMUMU,
  AZIR,
  NASUS,
  RAMMUS,
  RENEKTON,
  SIVIR,
  SKARNER,
  TALIYAH,
  XERATH,
  ZILEAN,
];

const PEAK_PERFORMANCE = "PEAK_PERFORMANCE";
const PEAK_PERFORMANCE_CHAMPS = [
  APHELIOS,
  AURELION_SOL,
  DIANA,
  LEONA,
  PANTHEON,
  SORAKA,
  TARIC,
  ZOE,
];

const CHEMTECH_COMRADES = "CHEMTECH_COMRADES";
const CHEMTECH_COMRADES_CHAMPS = [
  BLITZCRANK,
  DR_MUNDO,
  EKKO,
  JANNA,
  JINX,
  RENATA_GLASC,
  SINGED,
  TWITCH,
  URGOT,
  VIKTOR,
  VIKTOR,
  WARWICK,
  ZAC,
  ZERI,
  ZIGGS,
];

const ALL_HANDS_ON_DECK = "ALL_HANDS_ON_DECK";
const ALL_HANDS_ON_DECK_CHAMPS = [
  FIZZ,
  GANGPLANK,
  GRAVES,
  ILLAOI,
  MISS_FORTUNE,
  NAUTILUS,
  PYKE,
  TAHM_KENCH,
  TWISTED_FATE,
];

const ELEMENTAL_MY_DEAR_WATSON = "ELEMENTAL_MY_DEAR_WATSON";
const ELEMENTAL_MY_DEAR_WATSON_CHAMPS = [
  MALPHITE,
  NEEKO,
  NIDALEE,
  QIYANA,
  RENGAR,
  ZYRA,
];

const STRENGTH_ABOVE_ALL = "STRENGTH_ABOVE_ALL";
const STRENGTH_ABOVE_ALL_CHAMPS = [
  CASSIOPEIA,
  DARIUS,
  DRAVEN,
  KATARINA,
  KLED,
  LEBLANC,
  RELL,
  SAMIRA,
  SION,
  SWAIN,
  TALON,
  VLADIMIR,
];

const CALCULATED = "CALCULATED";
const CALCULATED_CHAMPS = [
  CAITLYN,
  CAMILLE,
  CORKI,
  EZREAL,
  HEIMERDINGER,
  JAYCE,
  ORIANNA,
  SERAPHINE,
  VI,
];

const SPOOKY_SCARY_SKELETONS = "SPOOKY_SCARY_SKELETONS";
const SPOOKY_SCARY_SKELETONS_CHAMPS = [
  ELISE,
  EVELYNN,
  FIDDLESTICKS,
  GWEN,
  HECARIM,
  KALISTA,
  KARTHUS,
  MAOKAI,
  SENNA,
  THRESH,
  VIEGO,
  YORICK,
];

const INHUMAN_SCREECHING_SOUNDS = "INHUMAN_SCREECHING_SOUNDS";
const INHUMAN_SCREECHING_SOUNDS_CHAMPS = [
  CHO_GATH,
  KAI_SA,
  KASSADIN,
  KHA_ZIX,
  KOG_MAW,
  MALZAHAR,
  REK_SAI,
  VEL_KOZ,
];

const ALL_GROUPS = [
  [IT_HAS_ULTIMATE_IN_THE_NAME, IT_HAS_ULTIMATE_IN_THE_NAME_CHAMPS],
  [GET_OVER_HERE, GET_OVER_HERE_CHAMPS],
  [HOLD_THAT_POSE, HOLD_THAT_POSE_CHAMPS],
  [WERE_GOOD_OVER_HERE, WERE_GOOD_OVER_HERE_CHAMPS],
  [NOWHERE_TO_HIDE, NOWHERE_TO_HIDE_CHAMPS],
  [WE_PROTEC, WE_PROTEC_CHAMPS],
  [ITS_A_TRAP, ITS_A_TRAP_CHAMPS],
  [THEY_JUST_DONT_DIE, THEY_JUST_DONT_DIE_CHAMPS],
  [WHERED_THEY_GO, WHERED_THEY_GO_CHAMPS],
  [SUMMONERS_ON_THE_RIFT, SUMMONERS_ON_THE_RIFT_CHAMPS],
  [IM_HELPING, IM_HELPING_CHAMPS],
  [FIVE_UNDER_FIVE, FIVE_UNDER_FIVE_CHAMPS],
  [FOR_DEMACIA, FOR_DEMACIA_CHAMPS],
  [ICE_ICE_BABY, ICE_ICE_BABY_CHAMPS],
  [EVERYBODY_WAS_WUJU_FIGHTING, EVERYBODY_WAS_WUJU_FIGHTING_CHAMPS],
  [THE_SUN_DISC_NEVER_SETS, THE_SUN_DISC_NEVER_SETS_CHAMPS],
  [PEAK_PERFORMANCE, PEAK_PERFORMANCE_CHAMPS],
  [CHEMTECH_COMRADES, CHEMTECH_COMRADES_CHAMPS],
  [ALL_HANDS_ON_DECK, ALL_HANDS_ON_DECK_CHAMPS],
  [ELEMENTAL_MY_DEAR_WATSON, ELEMENTAL_MY_DEAR_WATSON_CHAMPS],
  [STRENGTH_ABOVE_ALL, STRENGTH_ABOVE_ALL_CHAMPS],
  [CALCULATED, CALCULATED_CHAMPS],
  [SPOOKY_SCARY_SKELETONS, SPOOKY_SCARY_SKELETONS_CHAMPS],
  [INHUMAN_SCREECHING_SOUNDS, INHUMAN_SCREECHING_SOUNDS_CHAMPS],
];
const ALL_GROUPS_SET = ALL_GROUPS.map(([name, list]) => [name, new Set(list)]);

const GROUP_MAP = new Map(ALL_GROUPS);
const GROUP_MAP_SET = new Map(ALL_GROUPS_SET);

const FIVE_GROUPS = [
  SUMMONERS_ON_THE_RIFT,
  FIVE_UNDER_FIVE,
  FOR_DEMACIA,
  ICE_ICE_BABY,
  EVERYBODY_WAS_WUJU_FIGHTING,
  THE_SUN_DISC_NEVER_SETS,
  PEAK_PERFORMANCE,
  CHEMTECH_COMRADES,
  ALL_HANDS_ON_DECK,
  ELEMENTAL_MY_DEAR_WATSON,
  STRENGTH_ABOVE_ALL,
  CALCULATED,
  SPOOKY_SCARY_SKELETONS,
  INHUMAN_SCREECHING_SOUNDS,
];

const THREE_GROUPS = [
  IT_HAS_ULTIMATE_IN_THE_NAME,
  GET_OVER_HERE,
  HOLD_THAT_POSE,
  WERE_GOOD_OVER_HERE,
  NOWHERE_TO_HIDE,
  WE_PROTEC,
  ITS_A_TRAP,
  THEY_JUST_DONT_DIE,
  WHERED_THEY_GO,
  IM_HELPING,
];
